<?php

namespace App\Application\Rostering;

use App\Domain\Rostering\AssignmentSource;
use App\Domain\Rostering\AssignmentStatus;
use App\Domain\Rostering\GeneratedRosterResult;
use App\Domain\Rostering\ResolvedRosterPolicy;
use App\Domain\Rostering\RosterGenerationInput;
use App\Models\Doctor;
use App\Models\RosterAssignment;
use App\Models\RosterAssignmentExplanation;
use App\Models\RosterGenerationRun;
use App\Models\RosterPeriod;
use App\Models\User;

final class PersistGeneratedRosterBatch
{
    /** @return array{run: RosterGenerationRun, assignments: list<RosterAssignment>, changes: list<array<string, mixed>>} */
    public function handle(User $actor, RosterPeriod $period, ResolvedRosterPolicy $policy, RosterGenerationInput $input, GeneratedRosterResult $result): array
    {
        $runNumber = $period->generationRuns()->count() + 1;
        $run = RosterGenerationRun::query()->create(['identifier' => sprintf('GENERATION-%s-%04d', $period->identifier, $runNumber), 'roster_period_id' => $period->id, 'generator_name' => $policy->generatorName, 'generator_version' => $policy->generatorVersion, 'policy_fingerprint' => $policy->fingerprint, 'input_fingerprint' => $input->fingerprint, 'result_fingerprint' => $result->fingerprint, 'status' => 'committed', 'started_by' => $actor->id, 'started_at' => now(), 'completed_at' => now(), 'summary' => $result->toArray()['summary'], 'validation_status' => $result->status]);
        $doctors = Doctor::query()->whereIn('identifier', array_column($result->assignments, 'doctor_identifier'))->get()->keyBy('identifier');
        $days = $period->days()->get()->keyBy(fn ($day): string => $day->date->toDateString());
        $assignments = [];
        $changes = [];
        foreach ($result->assignments as $proposal) {
            $assignment = RosterAssignment::query()->create(['identifier' => 'PENDING', 'doctor_id' => $doctors[$proposal['doctor_identifier']]->id, 'roster_period_id' => $period->id, 'roster_day_id' => $days[$proposal['date']]->id, 'status' => AssignmentStatus::Assigned, 'source' => AssignmentSource::Generated, 'duty_code' => $proposal['duty_code'], 'credited_hours' => $proposal['credited_hours'], 'notes' => 'Generated by '.$run->identifier, 'created_by' => $actor->id]);
            $assignment->update(['identifier' => sprintf('ASSIGNMENT-%06d', $assignment->id)]);
            RosterAssignmentExplanation::query()->create(['roster_assignment_id' => $assignment->id, 'roster_generation_run_id' => $run->id, 'reason_codes' => $proposal['explanation']['reason_codes'], 'facts' => $proposal['explanation'], 'ranking_position' => $proposal['explanation']['ranking_position']]);
            $after = ['identifier' => $assignment->identifier, 'doctor_identifier' => $proposal['doctor_identifier'], 'roster_period_identifier' => $period->identifier, 'date' => $proposal['date'], 'status' => 'assigned', 'source' => 'generated', 'duty_code' => $proposal['duty_code'], 'credited_hours' => $proposal['credited_hours'], 'generation_identifier' => $run->identifier];
            $assignments[] = $assignment;
            $changes[] = ['change_type' => 'added', 'entity_identifier' => $assignment->identifier, 'before_value' => null, 'after_value' => $after];
        }

        return ['run' => $run, 'assignments' => $assignments, 'changes' => $changes];
    }
}
