<script setup lang="ts">
import { Form, Head, Link } from '@inertiajs/vue3';
import AppLayout from '@/layouts/AppLayout.vue';
import { index as periodsIndex, show as periodShow } from '@/routes/rostering/periods';
import { destroy, move, replace, store } from '@/routes/rostering/periods/assignments';
import { index as auditIndex } from '@/routes/rostering/periods/audit';
import { index as revisionsIndex } from '@/routes/rostering/periods/revisions';
import { preview as previewRoute, show as rosterShow } from '@/routes/rostering/periods/roster';

type Doctor = { identifier: string; name: string };
type AssignedDoctor = { assignment_identifier: string; doctor_identifier: string; doctor_name: string; credited_hours: string; duty_code: string };
type Finding = { severity: string; code: string; message: string; context: Record<string, unknown> };
type Day = { date: string; weekday: string; day_type: string; required_count: number; assigned_count: number; variance: number; staffing_status: string; assigned_doctors: AssignedDoctor[]; eligible_count: number; leave_count: number; unavailable_count: number; findings: Finding[] };
type MatrixRow = { doctor_identifier: string; doctor_name: string; dates: { date: string; state: string; assignment_identifier: string | null }[] };
type HoursRow = { doctor_identifier: string; doctor_name: string; required_hours: string; assigned_hours: string; variance: string; status: string; assigned_dates: string[] };
type Assignment = { identifier: string; doctor_identifier: string; doctor_name: string; date: string; credited_hours: string; duty_code: string; notes: string | null };
type Revision = { identifier: string; revision_number: number; reason: string; summary: Record<string, unknown>; validation_status: string; created_at: string | null };
type RevisionSummary = { current_revision: number; total_revisions: number; latest_reason: string | null; current_validation_status: string };
type AuditSummary = { total: number; by_action: Record<string, number> };
type Mutation = { operation: string; preview: boolean; revision_number: number | null; validation: { status: string; errors: number; warnings: number }; impact: Record<string, unknown> };

const props = defineProps<{ period: { identifier: string; title: string; status: string; start_date: string; end_date: string }; calendar: Day[]; weeks: { week: number; dates: Day[] }[]; doctor_matrix: MatrixRow[]; doctor_hours: HoursRow[]; assignments: Assignment[]; validation: { status: string; errors: number; warnings: number; findings: Finding[] }; doctors: Doctor[]; revision_summary: RevisionSummary; revisions: Revision[]; audit_summary: AuditSummary; audit: { action: string; entity_identifier: string; reason: string | null; created_at: string | null }[]; feedback: Mutation | null; preview: Mutation | null }>();
const breadcrumbs = [{ title: 'Roster periods', href: periodsIndex() }, { title: props.period.title, href: periodShow(props.period.identifier) }, { title: 'Manual roster', href: rosterShow(props.period.identifier) }];
const statusClass = (status: string) => status === 'fully_staffed' ? 'border-emerald-500 bg-emerald-50/60 dark:bg-emerald-950/20' : status === 'overstaffed' ? 'border-amber-500 bg-amber-50/60 dark:bg-amber-950/20' : 'border-red-500 bg-red-50/60 dark:bg-red-950/20';
</script>

<template>
    <Head title="Manual roster" />
    <AppLayout :breadcrumbs="breadcrumbs">
        <main class="flex flex-col gap-6 p-4 md:p-6">
            <header class="flex flex-col gap-2 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-sm text-muted-foreground">{{ period.identifier }} · revision {{ revisions[0]?.revision_number ?? 0 }}</p><h1 class="text-2xl font-semibold">Anaesthesia Department Draft Roster</h1><p class="text-muted-foreground">Manually Authored Draft — Not Yet Published</p></div><div class="rounded-lg border px-4 py-3 text-sm"><strong>Manual roster in progress</strong><br>{{ assignments.length }} assignments · {{ validation.status.replaceAll('_', ' ') }}</div></header>
            <div v-if="$page.props.errors.mutation" class="rounded-lg border border-red-500 bg-red-50 p-4 text-sm text-red-900">Mutation rejected: {{ $page.props.errors.mutation }}</div>
            <div v-if="feedback" class="rounded-lg border border-emerald-500 bg-emerald-50 p-4 text-sm text-emerald-950"><strong>Mutation succeeded.</strong> Revision {{ feedback.revision_number }} · {{ feedback.validation.status.replaceAll('_', ' ') }} · {{ feedback.validation.warnings }} warnings.</div>
            <div v-if="preview" class="rounded-lg border border-blue-500 bg-blue-50 p-4 text-sm text-blue-950"><strong>Dry-run preview:</strong> {{ preview.operation }} is permitted. No assignment, revision, or audit was created.</div>
            <Form v-bind="previewRoute.form(period.identifier)" class="grid gap-3 rounded-xl border border-blue-300 p-4 sm:grid-cols-[1fr_1fr_auto]" reset-on-success><input type="hidden" name="operation" value="add"><select name="doctor_identifier" required class="rounded-md border bg-background px-3 py-2 text-sm"><option value="">Preview doctor…</option><option v-for="doctor in doctors" :key="doctor.identifier" :value="doctor.identifier">{{ doctor.name }}</option></select><input type="date" name="date" required class="rounded-md border bg-background px-3 py-2 text-sm"><button class="rounded-md border border-blue-500 px-4 py-2 text-sm font-medium text-blue-700">Preview assignment</button></Form>
            <section class="rounded-xl border p-4"><h2 class="font-semibold">Legend and editing rules</h2><p class="mt-2 text-sm text-muted-foreground">✓ assigned · L leave · U unavailable · PW preferred work · PO preferred off · – not assigned · ! finding. Only assignments are editable. Availability and preference marks remain contextual evidence.</p></section>
            <section v-for="week in weeks" :key="week.week" class="grid gap-3"><h2 class="text-lg font-semibold">Week {{ week.week }}</h2><div class="grid gap-3 md:grid-cols-2 xl:grid-cols-7"><article v-for="day in week.dates" :key="day.date" class="rounded-xl border-2 p-3" :class="statusClass(day.staffing_status)"><div class="flex items-start justify-between gap-2"><div><strong>{{ day.weekday }}</strong><p class="text-xs">{{ day.date }}</p></div><span class="rounded-full border px-2 py-1 text-[10px] font-semibold uppercase">{{ day.staffing_status.replaceAll('_', ' ') }}</span></div><dl class="mt-3 grid grid-cols-2 gap-1 text-xs"><dt>Required</dt><dd class="text-right font-semibold">{{ day.required_count }}</dd><dt>Assigned</dt><dd class="text-right font-semibold">{{ day.assigned_count }}</dd><dt>Variance</dt><dd class="text-right font-semibold">{{ day.variance }}</dd><dt>Eligible</dt><dd class="text-right">{{ day.eligible_count }}</dd></dl><ul class="mt-3 space-y-1 text-xs"><li v-for="doctor in day.assigned_doctors" :key="doctor.assignment_identifier">✓ {{ doctor.doctor_name }}</li><li v-if="!day.assigned_doctors.length" class="text-muted-foreground">No assignments</li></ul><Form v-bind="store.form(period.identifier)" class="mt-3 grid gap-2" reset-on-success #default="{ processing }"><input type="hidden" name="date" :value="day.date"><select name="doctor_identifier" required class="w-full rounded-md border bg-background px-2 py-1 text-xs"><option value="">Assign doctor…</option><option v-for="doctor in doctors" :key="doctor.identifier" :value="doctor.identifier">{{ doctor.name }}</option></select><input type="hidden" name="duty_code" value="standard_day"><button class="rounded bg-primary px-2 py-1 text-xs text-primary-foreground" :disabled="processing">Assign</button></Form></article></div></section>
            <section class="grid gap-3"><h2 class="text-lg font-semibold">Doctor-by-date assignment matrix</h2><div class="overflow-x-auto rounded-xl border"><table class="min-w-max text-xs"><thead><tr class="bg-muted"><th class="sticky left-0 bg-muted p-2 text-left">Doctor</th><th v-for="day in calendar" :key="day.date" class="p-2"><span class="block">{{ day.weekday.slice(0, 3) }}</span>{{ day.date.slice(5) }}</th></tr></thead><tbody><tr v-for="row in doctor_matrix" :key="row.doctor_identifier" class="border-t"><th class="sticky left-0 bg-background p-2 text-left">{{ row.doctor_name }}</th><td v-for="cell in row.dates" :key="cell.date" class="p-2 text-center font-semibold">{{ cell.state }}</td></tr></tbody></table></div></section>
            <section class="grid gap-3"><h2 class="text-lg font-semibold">Assignment changes</h2><div class="grid gap-3 lg:grid-cols-2"><article v-for="assignment in assignments" :key="assignment.identifier" class="rounded-xl border p-4"><p class="font-semibold">{{ assignment.doctor_name }} · {{ assignment.date }}</p><p class="text-xs text-muted-foreground">{{ assignment.identifier }} · {{ assignment.credited_hours }} hours</p><div class="mt-3 grid gap-2 sm:grid-cols-3"><Form v-bind="move.form({ roster_period: period.identifier, roster_assignment: assignment.identifier })" class="grid gap-1"><input type="date" name="target_date" required class="rounded border bg-background px-2 py-1 text-xs"><button class="rounded border px-2 py-1 text-xs">Move</button></Form><Form v-bind="replace.form({ roster_period: period.identifier, roster_assignment: assignment.identifier })" class="grid gap-1"><select name="replacement_doctor_identifier" required class="rounded border bg-background px-2 py-1 text-xs"><option value="">Replacement…</option><option v-for="doctor in doctors" :key="doctor.identifier" :value="doctor.identifier">{{ doctor.name }}</option></select><button class="rounded border px-2 py-1 text-xs">Replace</button></Form><Form v-bind="destroy.form({ roster_period: period.identifier, roster_assignment: assignment.identifier })"><button class="h-full w-full rounded border border-red-500 px-2 py-1 text-xs text-red-700">Remove</button></Form></div></article></div></section>
            <section class="grid gap-3"><h2 class="text-lg font-semibold">Doctor assigned hours</h2><div class="overflow-x-auto rounded-xl border"><table class="w-full text-sm"><thead><tr class="bg-muted"><th class="p-2 text-left">Doctor</th><th>Required</th><th>Assigned</th><th>Variance</th><th>Status</th></tr></thead><tbody><tr v-for="doctor in doctor_hours" :key="doctor.doctor_identifier" class="border-t"><td class="p-2">{{ doctor.doctor_name }}</td><td class="text-center">{{ doctor.required_hours }}</td><td class="text-center">{{ doctor.assigned_hours }}</td><td class="text-center">{{ doctor.variance }}</td><td class="text-center">{{ doctor.status.replaceAll('_', ' ') }}</td></tr></tbody></table></div></section>
            <section class="grid gap-4 lg:grid-cols-3"><div class="rounded-xl border p-4"><h2 class="text-lg font-semibold">Revision summary</h2><dl class="mt-3 grid grid-cols-2 gap-2 text-sm"><dt>Current revision</dt><dd class="text-right font-semibold">{{ revision_summary.current_revision }}</dd><dt>Total revisions</dt><dd class="text-right">{{ revision_summary.total_revisions }}</dd><dt>Roster state after revision</dt><dd class="text-right">{{ revision_summary.current_validation_status.replaceAll('_', ' ') }}</dd></dl><p class="mt-3 text-sm text-muted-foreground">{{ revision_summary.latest_reason }}</p><Link :href="revisionsIndex(period.identifier)" class="mt-3 inline-block text-sm font-medium text-primary underline">Complete revision history</Link></div><div class="rounded-xl border p-4"><h2 class="text-lg font-semibold">Audit summary</h2><p class="mt-2 text-sm text-muted-foreground">{{ audit_summary.total }} exact-period audit entries</p><dl class="mt-3 grid grid-cols-[1fr_auto] gap-2 text-xs"><template v-for="(count, action) in audit_summary.by_action" :key="action"><dt>{{ action }}</dt><dd class="font-semibold">{{ count }}</dd></template></dl><Link :href="auditIndex(period.identifier)" class="mt-3 inline-block text-sm font-medium text-primary underline">Complete audit history</Link></div><div><h2 class="text-lg font-semibold">Validation</h2><p class="text-sm text-muted-foreground">{{ validation.errors }} errors · {{ validation.warnings }} warnings</p><div class="mt-2 grid gap-2"><article v-for="finding in validation.findings" :key="`${finding.code}-${JSON.stringify(finding.context)}`" class="rounded border p-3 text-sm"><strong>{{ finding.severity.toUpperCase() }} · {{ finding.code }}</strong><p>{{ finding.message }}</p></article></div></div></section>
            <section class="grid gap-4 lg:grid-cols-2"><div><h2 class="text-lg font-semibold">Recent revisions</h2><div class="mt-2 grid gap-2"><article v-for="revision in revisions" :key="revision.identifier" class="rounded border p-3 text-sm"><strong>Revision {{ revision.revision_number }} · {{ revision.validation_status.replaceAll('_', ' ') }}</strong><p>{{ revision.reason }}</p><small class="text-muted-foreground">{{ revision.identifier }}</small></article></div></div><div><h2 class="text-lg font-semibold">Recent period audit</h2><div class="mt-2 grid gap-2"><article v-for="entry in audit" :key="`${entry.action}-${entry.entity_identifier}-${entry.created_at}`" class="rounded border p-3 text-sm"><strong>{{ entry.action }}</strong><p>{{ entry.entity_identifier }}</p><small class="text-muted-foreground">{{ entry.reason }}</small></article></div></div></section>
        </main>
    </AppLayout>
</template>
