<script setup lang="ts">
import { Form, Head, Link } from '@inertiajs/vue3';
import InputError from '@/components/InputError.vue';
import AppLayout from '@/layouts/AppLayout.vue';
import { index, store } from '@/routes/rostering/periods';
const breadcrumbs = [{ title: 'Roster periods', href: index() }, { title: 'Create', href: store() }];
const fieldClass = 'w-full rounded-md border bg-background px-3 py-2 text-sm';
</script>
<template><Head title="Create roster period" /><AppLayout :breadcrumbs="breadcrumbs"><main class="mx-auto flex w-full max-w-3xl flex-col gap-5 p-4 md:p-6"><div><h1 class="text-2xl font-semibold">Create roster period</h1><p class="text-muted-foreground">Every inclusive date is created atomically with an explicit staffing requirement.</p></div><Form v-bind="store.form()" class="grid gap-5 rounded-lg border p-5" #default="{ errors, processing }"><label class="grid gap-1">Identifier<input name="identifier" placeholder="ROSTER-2026-09" :class="fieldClass" required /><InputError :message="errors.identifier" /></label><label class="grid gap-1">Title<input name="title" placeholder="September 2026 roster" :class="fieldClass" required /><InputError :message="errors.title" /></label><div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-1">Start date<input name="start_date" type="date" :class="fieldClass" required /></label><label class="grid gap-1">End date<input name="end_date" type="date" :class="fieldClass" required /></label><label class="grid gap-1">Default weekday doctors<input name="default_weekday_requirement" type="number" min="0" value="6" :class="fieldClass" required /></label><label class="grid gap-1">Default weekend doctors<input name="default_weekend_requirement" type="number" min="0" value="3" :class="fieldClass" required /></label></div><InputError :message="errors.end_date" /><label class="grid gap-1">Notes<textarea name="notes" :class="fieldClass" rows="4" /></label><div class="flex items-center justify-between"><Link class="text-sm text-muted-foreground underline" :href="index()">Cancel</Link><button class="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground" :disabled="processing">{{ processing ? 'Creating…' : 'Create roster period' }}</button></div></Form></main></AppLayout></template>
