<script setup lang="ts">
import { Head, router } from '@inertiajs/vue3';
import { preview as previewGeneration, store } from '@/actions/App/Http/Controllers/RosterGenerationController';
import AppLayout from '@/layouts/AppLayout.vue';

type Feasibility = { total_required_staffing_hours: string; total_doctor_target_hours: string; structural_hours_variance: string; classification: string; explanation: string };
type Quality = { classification: string; metrics: Record<string, string | number>; availability_use: Record<string, string | number>; limitations: string[] };
type RankedCandidate = { doctor_name: string; rank_position: number; selected: boolean; criteria: Record<string, string | number | boolean> };
type Preview = { fingerprint: string; feasibility: Feasibility; quality: Quality; summary: Record<string, string | number>; findings: { severity: string; code: string; message: string }[]; assignments: { doctor_name: string; date: string; explanation: { ranked_candidates: RankedCandidate[] } }[] };
interface Props { period: { identifier: string; title: string; status: string }; readiness: { doctor_count: number; date_count: number; required_slots: number; required_hours_complete: boolean; existing_assignments: number }; feasibility: Feasibility; generator: Record<string, unknown>; policy_calibration: { confirmed: string[]; provisional: string[]; unresolved_mandatory: string[]; unresolved_quality: string[]; blocks_generation: boolean; effective_policy_fingerprint: string }; preview?: Preview; committed?: { generation_identifier: string; revision_identifier: string } }
const props = defineProps<Props>();
</script>

<template>
    <AppLayout>
        <Head title="Draft roster generation" />
        <main class="mx-auto flex max-w-7xl flex-col gap-6 p-6">
            <header><p class="text-sm font-medium text-teal-700 dark:text-teal-300">Anaesthesia rostering</p><h1 class="text-3xl font-semibold">Generate draft roster</h1><p>{{ period.title }} · {{ period.status }}</p></header>
            <aside class="rounded-lg border border-amber-300 bg-amber-50 p-4 text-amber-950 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-100"><strong>This generator creates an editable draft.</strong> It does not guarantee mathematical optimality and must be reviewed before publication. Unspecified availability remains provisionally eligible.</aside>
            <section class="rounded-xl border border-amber-300 p-5"><h2 class="text-xl font-semibold">Department policy status</h2><p>{{ policy_calibration.confirmed.length }} confirmed · {{ policy_calibration.provisional.length }} provisional · {{ policy_calibration.unresolved_mandatory.length }} mandatory unresolved · {{ policy_calibration.unresolved_quality.length }} quality unresolved</p><p v-if="policy_calibration.blocks_generation" class="mt-2 font-semibold text-red-700">Preview is blocked until mandatory policy questions are resolved.</p><p class="mt-2 break-all font-mono text-xs">{{ policy_calibration.effective_policy_fingerprint }}</p></section>
            <section class="grid gap-4 md:grid-cols-4"><div class="rounded-lg border p-4"><b>Doctors</b><p class="text-2xl">{{ readiness.doctor_count }}</p></div><div class="rounded-lg border p-4"><b>Dates</b><p class="text-2xl">{{ readiness.date_count }}</p></div><div class="rounded-lg border p-4"><b>Required slots</b><p class="text-2xl">{{ readiness.required_slots }}</p></div><div class="rounded-lg border p-4"><b>Existing assignments</b><p class="text-2xl">{{ readiness.existing_assignments }}</p></div></section>
            <section class="space-y-3 rounded-xl border border-blue-300 bg-blue-50 p-5 dark:border-blue-800 dark:bg-blue-950/30"><h2 class="text-2xl font-semibold">Feasibility before generation</h2><div class="grid gap-3 sm:grid-cols-3"><div><b>Required staffing hours</b><p class="text-2xl">{{ feasibility.total_required_staffing_hours }}</p></div><div><b>Combined doctor targets</b><p class="text-2xl">{{ feasibility.total_doctor_target_hours }}</p></div><div><b>Structural variance</b><p class="text-2xl">{{ feasibility.structural_hours_variance }}</p></div></div><p>{{ feasibility.explanation }}</p></section>
            <div class="flex gap-3"><button :disabled="policy_calibration.blocks_generation" class="rounded bg-slate-700 px-4 py-2 text-white disabled:opacity-50" @click="router.post(previewGeneration(props.period.identifier).url)">Preview generation</button><button class="rounded bg-teal-700 px-4 py-2 text-white disabled:opacity-50" :disabled="!preview" @click="router.post(store(props.period.identifier).url)">Commit generated draft</button></div>
            <section v-if="preview" class="space-y-5"><h2 class="text-2xl font-semibold">Generation quality preview</h2><p class="font-mono text-xs">{{ preview.fingerprint }}</p><div class="rounded-xl border p-5"><h3 class="text-xl font-semibold">{{ preview.quality.classification.replaceAll('_', ' ') }}</h3><div class="mt-3 grid gap-3 md:grid-cols-4"><div v-for="(value, key) in preview.quality.metrics" :key="key" class="rounded border p-3"><b>{{ String(key).replaceAll('_', ' ') }}</b><p>{{ value }}</p></div></div></div><div class="rounded-xl border p-5"><h3 class="text-xl font-semibold">Availability use</h3><div class="mt-3 grid gap-3 md:grid-cols-3"><div v-for="(value, key) in preview.quality.availability_use" :key="key"><b>{{ String(key).replaceAll('_', ' ') }}</b><p>{{ value }}</p></div></div></div><div class="rounded-xl border p-5"><h3 class="text-xl font-semibold">Representative ranking decisions</h3><article v-for="assignment in preview.assignments.slice(0, 3)" :key="`${assignment.doctor_name}-${assignment.date}`" class="mt-3 border-t pt-3"><p><b>{{ assignment.doctor_name }}</b> was selected on {{ assignment.date }}.</p><ol class="mt-2 list-decimal pl-5 text-sm"><li v-for="candidate in assignment.explanation.ranked_candidates" :key="`${assignment.date}-${candidate.rank_position}`">{{ candidate.doctor_name }} ranked {{ candidate.rank_position }}: {{ Object.entries(candidate.criteria).map(([key, value]) => `${key.replaceAll('_', ' ')} ${value}`).join(' · ') }}</li></ol></article></div><div class="rounded-xl border p-5"><h3 class="text-xl font-semibold">Findings and limitations</h3><ul class="mt-2 space-y-2"><li v-for="finding in preview.findings" :key="finding.code" class="rounded border p-3">{{ finding.severity }} · {{ finding.code }} — {{ finding.message }}</li><li v-for="limitation in preview.quality.limitations" :key="limitation" class="text-sm text-muted-foreground">{{ limitation }}</li></ul></div></section>
            <p v-if="committed" class="rounded border border-green-300 bg-green-50 p-4 dark:border-green-800 dark:bg-green-950/30">Committed {{ committed.generation_identifier }} as {{ committed.revision_identifier }}.</p>
        </main>
    </AppLayout>
</template>
