<script setup lang="ts">
import { Form, Head } from '@inertiajs/vue3';
import AppLayout from '@/layouts/AppLayout.vue';
import { show } from '@/routes/rostering/periods';
import { edit, update } from '@/routes/rostering/periods/requirements';
type Doctor = { identifier: string; full_name: string; active: boolean; required_hours: string | null; source: string | null; notes: string | null };
const props = defineProps<{ period: { identifier: string; title: string }; doctors: Doctor[] }>();
const breadcrumbs = [{ title: props.period.title, href: show(props.period.identifier) }, { title: 'Required hours', href: edit(props.period.identifier) }];
</script>
<template><Head title="Doctor required hours" /><AppLayout :breadcrumbs="breadcrumbs"><main class="flex flex-col gap-5 p-4 md:p-6"><div><h1 class="text-2xl font-semibold">Doctor roster-period required hours</h1><p class="text-muted-foreground">Targets are explicit and manual. Contract notation is not converted.</p></div><Form v-bind="update.form(period.identifier)" class="grid gap-5" #default="{ processing }"><div class="overflow-x-auto rounded-lg border"><table class="w-full text-left text-sm"><thead class="bg-muted/50"><tr><th class="p-3">Doctor</th><th class="p-3">Required hours</th><th class="p-3">Source</th><th class="p-3">Notes</th></tr></thead><tbody><tr v-for="doctor in doctors" :key="doctor.identifier" class="border-t"><td class="p-3"><p class="font-medium">{{ doctor.full_name }}</p><p class="text-xs text-muted-foreground">{{ doctor.active ? 'Active' : 'Inactive' }}</p></td><td class="p-3"><input :name="`requirements[${doctor.identifier}][required_hours]`" type="number" min="0" step="0.25" :value="doctor.required_hours" class="w-28 rounded-md border bg-background px-3 py-2" :aria-label="`Required hours for ${doctor.full_name}`" /></td><td class="p-3">{{ doctor.source ?? 'manual when saved' }}</td><td class="p-3"><input :name="`requirements[${doctor.identifier}][notes]`" :value="doctor.notes" class="min-w-48 rounded-md border bg-background px-3 py-2" :aria-label="`Requirement notes for ${doctor.full_name}`" /></td></tr></tbody></table></div><button class="w-fit rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground" :disabled="processing">{{ processing ? 'Saving…' : 'Save explicit targets' }}</button></Form></main></AppLayout></template>
