<script setup lang="ts">
import { Form, Head, Link } from '@inertiajs/vue3';
import AppLayout from '@/layouts/AppLayout.vue';
import { show, transition } from '@/routes/rostering/periods';
import { index as assignments } from '@/routes/rostering/periods/assignments';
import { show as availability } from '@/routes/rostering/periods/availability';
import { edit as requirements } from '@/routes/rostering/periods/requirements';
import { edit as staffing } from '@/routes/rostering/periods/staffing';
type Period = { identifier:string;title:string;start_date:string;end_date:string;status:string;notes:string|null;days_count:number;doctor_requirements_count:number;assignments_count:number };
type Finding = {severity:string;code:string;message:string};
const props=defineProps<{period:Period;findings:Finding[];allowedTransitions:string[]}>();
const breadcrumbs=[{title:'Roster periods',href:'/rostering/periods'},{title:props.period.title,href:show(props.period.identifier)}];
</script>
<template><Head :title="period.title" /><AppLayout :breadcrumbs="breadcrumbs"><main class="flex flex-col gap-6 p-4 md:p-6"><header><p class="text-sm text-muted-foreground">{{ period.identifier }}</p><h1 class="text-2xl font-semibold">{{ period.title }}</h1><p class="text-muted-foreground">{{ period.start_date }} – {{ period.end_date }} · {{ period.status.replaceAll('_',' ') }}</p></header><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Link :href="staffing(period.identifier)" class="rounded-lg border p-4"><p class="font-semibold">Staffing requirements</p><p class="text-sm text-muted-foreground">{{ period.days_count }} roster days</p></Link><Link :href="requirements(period.identifier)" class="rounded-lg border p-4"><p class="font-semibold">Doctor required hours</p><p class="text-sm text-muted-foreground">{{ period.doctor_requirements_count }} explicit targets</p></Link><Link :href="availability(period.identifier)" class="rounded-lg border p-4"><p class="font-semibold">Requests and availability</p><p class="text-sm text-muted-foreground">Calendar, requests, conflicts</p></Link><Link :href="assignments(period.identifier)" class="rounded-lg border p-4"><p class="font-semibold">Assignments</p><p class="text-sm text-muted-foreground">{{ period.assignments_count }} stored · editing deferred</p></Link></div><section class="grid gap-3"><h2 class="text-lg font-semibold">Foundation and request validation</h2><div v-if="findings.length" class="grid gap-2"><div v-for="finding in findings" :key="`${finding.code}-${finding.message}`" class="rounded-md border p-3 text-sm"><span class="font-semibold uppercase">{{ finding.severity }}</span> · {{ finding.message }} <span class="text-muted-foreground">({{ finding.code }})</span></div></div><p v-else class="rounded-md border p-4 text-sm text-muted-foreground">No readiness findings.</p></section><section v-if="allowedTransitions.length" class="grid gap-3"><h2 class="text-lg font-semibold">Next lifecycle action</h2><Form v-for="status in allowedTransitions" :key="status" v-bind="transition.form(period.identifier)" class="flex items-center gap-3"><input type="hidden" name="status" :value="status" /><button class="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Move to {{ status.replaceAll('_',' ') }}</button></Form></section></main></AppLayout></template>
