<script setup lang="ts">
import { Form, Head, Link } from '@inertiajs/vue3';
import InputError from '@/components/InputError.vue';
import AppLayout from '@/layouts/AppLayout.vue';
import { destroy, index, store, update } from '@/routes/rostering/doctors';
type Option = { value: string; label: string };
type Doctor = { identifier: string; full_name: string; employee_identifier: string | null; employment_type: string; active: boolean; contracted_hours: string | null; contracted_hours_period: string | null; standard_daily_hours: string; notes: string | null };
const props = defineProps<{ doctor: Doctor | null; employmentTypes: Option[]; contractPeriods: Option[] }>();
const breadcrumbs = [{ title: 'Doctors', href: index() }, { title: props.doctor ? props.doctor.full_name : 'Register doctor', href: props.doctor ? update(props.doctor.identifier) : store() }];
const fieldClass = 'w-full rounded-md border bg-background px-3 py-2 text-sm';
</script>
<template><Head :title="doctor ? `Edit ${doctor.full_name}` : 'Register doctor'" /><AppLayout :breadcrumbs="breadcrumbs"><main class="mx-auto flex w-full max-w-3xl flex-col gap-5 p-4 md:p-6"><div><h1 class="text-2xl font-semibold">{{ doctor ? 'Edit doctor' : 'Register doctor' }}</h1><p class="text-muted-foreground">Contract notation is descriptive; required period hours are set separately.</p></div><Form v-bind="doctor ? update.form(doctor.identifier) : store.form()" class="grid gap-5 rounded-lg border p-5" #default="{ errors, processing }"><label class="grid gap-1">Full name<input name="full_name" :value="doctor?.full_name" :class="fieldClass" required /><InputError :message="errors.full_name" /></label><label class="grid gap-1">Employee identifier<input name="employee_identifier" :value="doctor?.employee_identifier" :class="fieldClass" /><InputError :message="errors.employee_identifier" /></label><div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-1">Employment type<select name="employment_type" :class="fieldClass" required><option v-for="option in employmentTypes" :key="option.value" :value="option.value" :selected="doctor?.employment_type === option.value">{{ option.label }}</option></select></label><label class="grid gap-1">Standard daily hours<input name="standard_daily_hours" type="number" step="0.25" min="0.25" :value="doctor?.standard_daily_hours ?? 8" :class="fieldClass" required /></label><label class="grid gap-1">Contracted hours<input name="contracted_hours" type="number" step="0.25" min="0" :value="doctor?.contracted_hours" :class="fieldClass" /></label><label class="grid gap-1">Contract period<select name="contracted_hours_period" :class="fieldClass"><option value="">Not specified</option><option v-for="option in contractPeriods" :key="option.value" :value="option.value" :selected="doctor?.contracted_hours_period === option.value">{{ option.label }}</option></select></label></div><label class="grid gap-1">Notes<textarea name="notes" :value="doctor?.notes" :class="fieldClass" rows="4" /></label><div class="flex items-center justify-between gap-4"><Link class="text-sm text-muted-foreground underline" :href="index()">Cancel</Link><button class="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground" :disabled="processing">{{ processing ? 'Saving…' : 'Save doctor' }}</button></div></Form><Form v-if="doctor?.active" v-bind="destroy.form(doctor.identifier)" class="rounded-lg border border-destructive/30 p-5" #default="{ processing }"><input type="hidden" name="reason" value="Deactivated by roster administrator" /><button class="text-sm font-medium text-destructive underline" :disabled="processing">Deactivate doctor</button></Form></main></AppLayout></template>
