<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3';
import AppLayout from '@/layouts/AppLayout.vue';
import { create, edit, index } from '@/routes/rostering/doctors';
type Doctor = { identifier: string; full_name: string; employee_identifier: string | null; employment_type: string; active: boolean; standard_daily_hours: string };
defineProps<{ doctors: Doctor[] }>();
const breadcrumbs = [{ title: 'Doctors', href: index() }];
</script>
<template><Head title="Doctors" /><AppLayout :breadcrumbs="breadcrumbs"><main class="flex flex-col gap-5 p-4 md:p-6"><header class="flex items-center justify-between gap-4"><div><h1 class="text-2xl font-semibold">Doctors</h1><p class="text-muted-foreground">Stable records for active and historical clinicians.</p></div><Link class="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground" :href="create()">Register doctor</Link></header><div class="overflow-x-auto rounded-lg border"><table class="w-full text-left text-sm"><thead class="bg-muted/50"><tr><th class="p-3">Doctor</th><th class="p-3">Employment</th><th class="p-3">Daily hours</th><th class="p-3">Status</th><th class="p-3"></th></tr></thead><tbody><tr v-for="doctor in doctors" :key="doctor.identifier" class="border-t"><td class="p-3"><p class="font-medium">{{ doctor.full_name }}</p><p class="text-xs text-muted-foreground">{{ doctor.identifier }}<span v-if="doctor.employee_identifier"> · {{ doctor.employee_identifier }}</span></p></td><td class="p-3">{{ doctor.employment_type.replaceAll('_', ' ') }}</td><td class="p-3">{{ doctor.standard_daily_hours }}</td><td class="p-3">{{ doctor.active ? 'Active' : 'Inactive' }}</td><td class="p-3 text-right"><Link class="text-primary underline" :href="edit(doctor.identifier)">Edit</Link></td></tr><tr v-if="doctors.length === 0"><td colspan="5" class="p-8 text-center text-muted-foreground">No doctors have been registered.</td></tr></tbody></table></div></main></AppLayout></template>
